config/routes.rb
Rails.application.routes.draw do
  resources :bicycles
  resources :users
  resources :reservations do
    collection do
      get 'time_reservations'
    end
  end
  root 'bicycles#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bicycle.rb
class Bicycle < ApplicationRecord

    def available_from
        av_f= Reservation.where(["date_from <= ? and bicycle_id = ?", Time.current, id]).order("date_to ASC").last
        if av_f.present? and av_f.date_to>Time.current
            "from " + av_f.date_to.strftime("%H:%M %a %d-%b-%Y")
        else "from now" 
        end
    end

    def available_till
        af_t= Reservation.where(["date_from > ? and bicycle_id = ?", Time.current, id]).order("date_from ASC").first
        if af_t.present?
            "till " + af_t.date_from.strftime("%H:%M %a %d-%b-%Y")
        else "with no end time" 
        end
    end

    validates :frame_number, :name, :description, presence:true
    validates :frame_number, uniqueness: true
    validates :name, uniqueness: true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :bicycle
  belongs_to :user

  def full_type
    case reserv_type
      when "S" 
        "In Service"
      when "R" 
        "Reservation"
      else 
        "Unavailable"
    end
  end

  validates :bicycle, :date_from, :date_to, :user, :description, :reserv_type, presence:true 
  validate :reserv_time

  def reserv_time  
    rt = Reservation.where(["date_from < ? and date_to > ? and bicycle_id = ? and id <> ?", date_to, date_from, bicycle_id, id]).first
    
    if rt.present?
      errors.add(:base, "Unavailable for reservation in the selected period!")
    end
    
  end

end

app/models/user.rb
class User < ApplicationRecord
    def user_name
        "#{name} #{surname}"
      end

      validates :name, :surname, presence:true
      validates :name, uniqueness: { scope: :surname, message: " and Surname combination already exists!" }
end

    

  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bicycles_controller.rb
class BicyclesController < ApplicationController
  before_action :set_bicycle, only: [:show, :edit, :update, :destroy]

  # GET /bicycles
  # GET /bicycles.json
  def index
     @bicycles = Bicycle.all #.order('available_from ASC')
     @bicycles = Bicycle.all.sort {|a,b| b.available_from <=> a.available_from }
  end

  # GET /bicycles/1
  # GET /bicycles/1.json
  def show
    @reservations = Reservation.where(["bicycle_id = ?", @bicycle.id])
  end

  # GET /bicycles/new
  def new
    @bicycle = Bicycle.new
  end

  # GET /bicycles/1/edit
  def edit
  end

  # POST /bicycles
  # POST /bicycles.json
  def create
    @bicycle = Bicycle.new(bicycle_params)

    respond_to do |format|
      if @bicycle.save
        format.html { redirect_to @bicycle, notice: 'Bicycle was successfully created.' }
        format.json { render :show, status: :created, location: @bicycle }
      else
        format.html { render :new }
        format.json { render json: @bicycle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bicycles/1
  # PATCH/PUT /bicycles/1.json
  def update
    respond_to do |format|
      if @bicycle.update(bicycle_params)
        format.html { redirect_to @bicycle, notice: 'Bicycle was successfully updated.' }
        format.json { render :show, status: :ok, location: @bicycle }
      else
        format.html { render :edit }
        format.json { render json: @bicycle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bicycles/1
  # DELETE /bicycles/1.json
  def destroy
    @bicycle.destroy
    respond_to do |format|
      format.html { redirect_to bicycles_url, notice: 'Bicycle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bicycle
      @bicycle = Bicycle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bicycle_params
      params.require(:bicycle).permit(:frame_number, :name, :description)
    end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]

  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.all
  end

  def time_reservations
    @reservations = Reservation.all
    render json: @reservations.to_json(include: { user: { methods: [:user_name] }, bicycle: {} })
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to @reservation, notice: 'Reservation was successfully created.' }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: 'Reservation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_params
      params.require(:reservation).permit(:bicycle_id, :date_from, :date_to, :user_id, :description, :reserv_type)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.order('name ASC, surname ASC')

  end

  # GET /users/1
  # GET /users/1.json
  def show
    @reservations = Reservation.where(["user_id = ?", @user.id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :surname)
    end

    
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bicycles_helper.rb
module BicyclesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bicycles/_form.html.erb
<%= form_with(model: bicycle, local: true) do |form| %>
  <% if bicycle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bicycle.errors.count, "error") %> prohibited this bicycle from being saved:</h2>

      <ul>
      <% bicycle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :frame_number %>
    <%= form.text_field :frame_number %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bicycles/edit.html.erb
<h1>Editing Bicycle</h1>

<%= render 'form', bicycle: @bicycle %>

<%= link_to 'Show', @bicycle %> |
<%= link_to 'Back', bicycles_path %>

app/views/bicycles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bicycles</h1>
<%= link_to 'Add Bicycle', new_bicycle_path %>
<div class="grid-container" >
        <% @bicycles.each do |bicycle| %>
            <figure class="cycle shadow-lg p-3 mb-5 bg-white rounded">
                <h5><%= bicycle.name %> (<%= bicycle.frame_number %>)</h5>
                <img class="img-thumbnail" src="" alt="">
                <figcaption> <table>
                              <tr>
                                <td colspan="2">
                                <strong>First available time</strong> 
                                </td>
                              </tr>
                              <tr>
                                <td><%= bicycle.available_from %> </td>
                                <td><%= bicycle.available_till %> </td>               
                              </tr>
                              <tr>  
                                <td><%= link_to 'Show', bicycle %></td>
                                <td><%= link_to 'Reserve', new_reservation_path %></td>
                              </tr>
                            </table>
                </figcaption>
                
            </figure>
        <% end %>
</div>

<br>

app/views/bicycles/new.html.erb
<h1>New Bicycle</h1>

<%= render 'form', bicycle: @bicycle %>

<%= link_to 'Back', bicycles_path %>

app/views/bicycles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Frame number:</strong>
  <%= @bicycle.frame_number %>
</p>

<p>
  <strong>Name:</strong>
  <%= @bicycle.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @bicycle.description %>
</p>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Bicycle</th>
      <th scope="col">Reserved from</th>
      <th scope="col">Till</th>
      <th scope="col">Employee</th>
      <th scope="col">Description</th>
      <th scope="col">Reservation Type</th>
      <th  scope="col" colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
      <tr data-reservation-id="<%= reservation.id %>">
        <td data-reservation-attribute="bicycle"><%= reservation.bicycle.name %></td>
        <td data-reservation-attribute="date_from"><%= reservation.date_from.strftime("%H:%M %a %d-%b-%Y") %></td>
        <td data-reservation-attribute="date_to"><%= reservation.date_to.strftime("%H:%M %a %d-%b-%Y") %></td>
        <td data-reservation-attribute="user"><%= reservation.user.user_name %></td>
        <td data-reservation-attribute="description"><%= reservation.description %></td>
        <td data-reservation-attribute="full_type"><%= reservation.full_type %></td>
        
        <td><%= link_to 'Show', reservation %></td>
        <td><%= link_to 'Edit', edit_reservation_path(reservation) %></td>
        <td><%= link_to 'Destroy', reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<%= link_to 'Edit', edit_bicycle_path(@bicycle) %> |
<%= link_to 'Destroy', @bicycle, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', bicycles_path %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Velo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4 sticky-top">
          <a class="navbar-brand" href="/">ReservMe</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item">            
                <%= link_to 'Bicycles', bicycles_path, html_options = {:class=>"nav-link"} %> 
              </li>
              <li class="nav-item">
                <%= link_to 'Users', users_path, html_options = {:class=>"nav-link"} %> 
              </li>
              <li class="nav-item">
                <%= link_to 'Reservations', reservations_path, html_options = {:class=>"nav-link"} %> 
              </li>
              
            </ul>
              
          </div>
        </nav>
  <div class="container">
    <div class="row">
      <div class="col-md-12 col-lg-12">
        <%= yield %>
      </div>
    </div>
  </div>
  </body>
</html>

app/views/reservations/_form.html.erb
<%= form_with(model: reservation, local: true) do |form| %>
  <% if reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :bicycle_id %>
    <%= form.collection_select :bicycle_id, Bicycle.all, :id, :name, prompt:true %>
  </div>

  <div class="field">
    <%= form.label :date_from %>
    <%= form.datetime_select :date_from %>
  </div>

  <div class="field">
    <%= form.label :date_to %>
    <%= form.datetime_select :date_to %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.collection_select :user_id, User.all, :id, :user_name, prompt:true %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :reserv_type, 'Reservation Type' %>
    <%= form.select :reserv_type, [['In Service','S'],['Unavailable','U'],['Reservation','R']] %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reservations</h1>
<%= link_to 'New Reservation', new_reservation_path %>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Bicycle</th>
      <th scope="col">Reserved from</th>
      <th scope="col">Till</th>
      <th scope="col">Employee</th>
      <th scope="col">Description</th>
      <th scope="col">Reservation Type</th>
      <th  scope="col" colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
      <tr data-reservation-id="<%= reservation.id %>">
        <td data-reservation-attribute="bicycle"><%= reservation.bicycle.name %></td>
        <td data-reservation-attribute="date_from"><%= reservation.date_from.strftime("%H:%M %a %d-%b-%Y") %></td>
        <td data-reservation-attribute="date_to"><%= reservation.date_to.strftime("%H:%M %a %d-%b-%Y") %></td>
        <td data-reservation-attribute="user"><%= reservation.user.user_name %></td>
        <td data-reservation-attribute="description"><%= reservation.description %></td>
        <td data-reservation-attribute="full_type"><%= reservation.full_type %></td>
        
        <td><%= link_to 'Show', reservation %></td>
        <td><%= link_to 'Edit', edit_reservation_path(reservation) %></td>
        <td><%= link_to 'Destroy', reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>





<br>

app/views/reservations/new.html.erb
<h1>New Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'All Reservations', reservations_path %> |
<%= link_to 'All Bicycles', bicycles_path %>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bicycle:</strong>
  <%= @reservation.bicycle.name %>
</p>

<p>
  <strong>Date from:</strong>
  <%= @reservation.date_from.strftime("%H:%M %a %d-%b-%Y") %>
</p>

<p>
  <strong>Date to:</strong>
  <%= @reservation.date_to.strftime("%H:%M %a %d-%b-%Y") %>
</p>

<p>
  <strong>User:</strong>
  <%= @reservation.user.user_name  %>
</p>

<p>
  <strong>Description:</strong>
  <%= @reservation.description %>
</p>

<p>
  <strong>Reservation Type:</strong>
  <%= @reservation.full_type %>
</p>

<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :surname %>
    <%= form.text_field :surname %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>
<%= link_to 'New User', new_user_path %>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Surname</th>
      <th colspan="3" scope="col"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.surname %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @user.surname %>
</p>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Bicycle</th>
      <th scope="col">Reserved from</th>
      <th scope="col">Till</th>
      <th scope="col">Employee</th>
      <th scope="col">Description</th>
      <th scope="col">Reservation Type</th>
      <th  scope="col" colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
      <tr data-reservation-id="<%= reservation.id %>">
        <td data-reservation-attribute="bicycle"><%= reservation.bicycle.name %></td>
        <td data-reservation-attribute="date_from"><%= reservation.date_from.strftime("%H:%M %a %d-%b-%Y") %></td>
        <td data-reservation-attribute="date_to"><%= reservation.date_to.strftime("%H:%M %a %d-%b-%Y") %></td>
        <td data-reservation-attribute="user"><%= reservation.user.user_name %></td>
        <td data-reservation-attribute="description"><%= reservation.description %></td>
        <td data-reservation-attribute="full_type"><%= reservation.full_type %></td>
        
        <td><%= link_to 'Show', reservation %></td>
        <td><%= link_to 'Edit', edit_reservation_path(reservation) %></td>
        <td><%= link_to 'Destroy', reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>